import type { Metadata } from "next";
import {
  LegalPage,
  LegalSection,
  LegalSubHeading,
  LegalSubCard,
  LegalDefinition,
  LegalBulletList,
  LegalSubBulletList,
  LegalCallout,
  LegalLink,
} from "@/components/legal/LegalShell";

export const metadata: Metadata = {
  title: "Privacy Policy — ElarisLabs",
  description: "Privacy Policy for ElarisLabs.",
};

export default function PrivacyPolicyPage() {
  return (
    <LegalPage
      title="Privacy Policy"
      effective="January 10, 2026"
      updated="January 10, 2026"
    >
      <LegalSection num={1} title="Who we are">
        <p>
          This Privacy Policy explains how ElarisLabs (&quot;ElarisLabs,&quot;
          &quot;we,&quot; &quot;us&quot;) collects, uses, shares, and protects
          information when you use elarislabs.ai, our apps, dashboards, APIs,
          and related services (collectively, the &quot;Services&quot;).
        </p>
        <LegalCallout>
          <strong className="text-bone">Contact:</strong>{" "}
          <LegalLink href="mailto:privacy@elarislabs.ai">
            privacy@elarislabs.ai
          </LegalLink>
        </LegalCallout>
      </LegalSection>

      <LegalSection num={2} title="What this policy covers">
        <p>This policy covers:</p>
        <LegalBulletList
          items={[
            "Visitors to our website",
            "Customers and users of the Services (including trials and betas)",
            "Leads and marketing contacts",
            "Business partners and vendors",
          ]}
        />
        <p>
          It does not cover third-party websites or services that you access
          via links from our Services.
        </p>
      </LegalSection>

      <LegalSection num={3} title="Key definitions (AI-specific)">
        <div className="grid gap-3">
          <LegalDefinition
            term="Personal Data"
            desc="Information that identifies or can reasonably be linked to an individual."
          />
          <LegalDefinition
            term="Customer Content"
            desc="Content you submit to the Services, including prompts, text, brand briefs, images, videos, logos, product photos, fonts, creative guidelines, and files."
          />
          <LegalDefinition
            term="Outputs"
            desc="Content generated by the Services based on Customer Content (for example, ad copy, creative concepts, images, videos, variants, and metadata)."
          />
          <LegalDefinition
            term="Account Data"
            desc="Information tied to your account (name, email, organization, role, billing)."
          />
          <LegalDefinition
            term="Usage Data"
            desc="Telemetry and logs about how the Services are used."
          />
        </div>
      </LegalSection>

      <LegalSection num={4} title="Information we collect">
        <LegalSubHeading letter="A">Information you provide</LegalSubHeading>
        <div className="grid gap-3">
          <LegalSubCard title="Account and profile data">
            <LegalSubBulletList
              items={[
                "Name, email, password (hashed), organization name, role, and workspace settings",
                "Team member invites and permissions",
              ]}
            />
          </LegalSubCard>
          <LegalSubCard title="Billing and transaction data">
            <LegalSubBulletList
              items={[
                "Billing address, tax identifiers (if applicable), subscription plan, invoices",
                "Payment details are typically processed by our payment processor; we generally receive tokens and limited payment metadata rather than full card numbers.",
              ]}
            />
          </LegalSubCard>
          <LegalSubCard title="Customer Content">
            <LegalSubBulletList
              items={[
                "Prompts, briefs, brand assets, uploaded files, campaign inputs",
                "Generated outputs you save, export, publish, or share via the Services",
                "Feedback you submit (ratings, comments, bug reports)",
              ]}
            />
          </LegalSubCard>
          <LegalSubCard title="Support and communications">
            <LegalSubBulletList
              items={[
                "Emails, chat messages, and call notes when you contact us",
                "Attachments you send to support",
              ]}
            />
          </LegalSubCard>
        </div>

        <LegalSubHeading letter="B">
          Information collected automatically
        </LegalSubHeading>
        <div className="grid gap-3">
          <LegalSubCard title="Device and browser data">
            <LegalSubBulletList
              items={[
                "IP address, device identifiers, browser type, OS, language, and approximate location (derived from IP)",
              ]}
            />
          </LegalSubCard>
          <LegalSubCard title="Usage and log data">
            <LegalSubBulletList
              items={[
                "Feature usage, clicks, timestamps, pages viewed, error logs, performance metrics",
                "Security logs (authentication events, suspicious activity signals)",
              ]}
            />
          </LegalSubCard>
          <LegalSubCard title="Cookies and similar technologies">
            <LegalSubBulletList
              items={[
                "Essential cookies for login and session integrity",
                "Analytics cookies (if enabled)",
                "Preference cookies (language, UI settings)",
                "You can manage cookies through your browser settings and, where available, our cookie banner/preferences center.",
              ]}
            />
          </LegalSubCard>
        </div>

        <LegalSubHeading letter="C">
          Information from third parties
        </LegalSubHeading>
        <LegalBulletList
          items={[
            "Identity providers (if you use SSO)",
            "Payment processors (payment confirmation, fraud signals)",
            "Analytics and marketing platforms (campaign attribution)",
            "Public sources or enrichment tools (for business contact data, where permitted)",
          ]}
        />
      </LegalSection>

      <LegalSection num={5} title="How we use information">
        <p>We use information to:</p>
        <div className="grid gap-3">
          <LegalDefinition
            term="Provide and operate the Services"
            desc="Create accounts, authenticate users, manage workspaces, process prompts and assets to generate Outputs and creative variants, store and retrieve your projects, settings, and exports."
          />
          <LegalDefinition
            term="Improve performance and reliability"
            desc="Debug issues, monitor uptime, prevent crashes, conduct testing including beta testing and new feature rollout."
          />
          <LegalDefinition
            term="Security, safety, and abuse prevention"
            desc="Detect fraud, account compromise, malware, prompt abuse, and policy violations; enforce our acceptable use rules and protect users."
          />
          <LegalDefinition
            term="Customer support"
            desc="Respond to questions, troubleshoot problems, and fulfill requests."
          />
          <LegalDefinition
            term="Billing and administration"
            desc="Process payments, manage subscriptions, send invoices, and handle taxes."
          />
          <LegalDefinition
            term="Communications and marketing"
            desc="Service announcements, security alerts, onboarding guidance, marketing updates (you can opt out of marketing emails anytime)."
          />
          <LegalDefinition
            term="Legal compliance"
            desc="Comply with applicable laws, respond to lawful requests, and maintain records."
          />
        </div>
      </LegalSection>

      <LegalSection
        num={6}
        title="AI processing, model improvement, and training controls"
      >
        <p>
          Because we provide AI-driven creative generation, we process Customer
          Content (including prompts and brand assets) to produce Outputs.
        </p>
        <div className="grid gap-3">
          <LegalSubCard title="A. How your content is processed">
            Your prompts and assets are processed by our systems to generate
            Outputs and variants. We may use third-party infrastructure (cloud
            hosting, storage, content delivery) and, depending on your
            configuration, third-party AI model providers to perform inference
            (generation).
          </LegalSubCard>
          <LegalSubCard title="B. Default: Customer Content is not used to train foundation models">
            By default, we do not use your Customer Content (including prompts
            and Outputs) to train or fine-tune our foundation models. This
            mirrors common enterprise-style AI data controls.
          </LegalSubCard>
          <LegalSubCard title="C. Optional opt-in for improvement">
            We may offer product settings that allow you (or your organization
            admin) to opt in to share certain content to help improve model
            quality, evaluation, and features. If you opt in, we may use
            shared content to evaluate and improve the Services (including
            internal fine-tuning or supervised review pipelines). We apply
            safeguards designed to minimize exposure of sensitive data.
          </LegalSubCard>
          <LegalSubCard title="D. Safety and abuse review carve-outs">
            Even if you do not opt in, we may review limited content as
            necessary to investigate security incidents, fraud, and abuse;
            enforce policies and prevent harmful use; and comply with legal
            obligations.
          </LegalSubCard>
          <LegalSubCard title="E. What we recommend you avoid sharing">
            Unless you have a signed agreement that explicitly permits it, do
            not upload highly sensitive personal data (e.g., government IDs,
            biometrics, medical records) or secrets that you cannot risk
            exposing (e.g., private keys, credentials). Contact us for
            enterprise configuration and a Data Processing Addendum (DPA) if
            needed.
          </LegalSubCard>
        </div>
      </LegalSection>

      <LegalSection
        num={7}
        title="Legal bases for processing (EEA, UK, Switzerland)"
      >
        <p>If you are in the EEA/UK/Switzerland, we rely on:</p>
        <div className="grid sm:grid-cols-2 gap-3">
          <LegalDefinition
            term="Contract"
            desc="To provide the Services you request."
          />
          <LegalDefinition
            term="Legitimate interests"
            desc="To secure, maintain, and improve the Services."
          />
          <LegalDefinition
            term="Consent"
            desc="For optional analytics cookies and marketing where required."
          />
          <LegalDefinition
            term="Legal obligation"
            desc="To comply with applicable laws."
          />
        </div>
      </LegalSection>

      <LegalSection num={8} title="How we share information">
        <p>We may share information with:</p>
        <div className="grid gap-3">
          <LegalDefinition
            term="Service providers and processors"
            desc="Hosting, storage, analytics, customer support tools, email delivery, payment processing, fraud prevention. They process data under contractual obligations consistent with this policy."
          />
          <LegalDefinition
            term="AI and infrastructure providers"
            desc="Model inference providers (if used), compute providers, CDN, and related vendors needed to run the Services."
          />
          <LegalDefinition
            term="Affiliates"
            desc="If we operate through group entities, we may share data within our corporate family for internal administration and delivery of Services."
          />
          <LegalDefinition
            term="Business transfers"
            desc="If we are involved in a merger, acquisition, financing, or sale of assets, data may be transferred as part of that transaction."
          />
          <LegalDefinition
            term="Legal and safety"
            desc="If required by law or necessary to protect rights, safety, and security (for example, responding to valid legal process)."
          />
        </div>
      </LegalSection>

      <LegalSection num={9} title="International data transfers">
        <p>
          We may transfer Personal Data to countries other than where you
          live. Where required, we use safeguards such as:
        </p>
        <LegalBulletList
          items={[
            "Standard Contractual Clauses (SCCs)",
            "Equivalent legal transfer mechanisms",
            "Additional security measures (as appropriate)",
          ]}
        />
      </LegalSection>

      <LegalSection num={10} title="Data retention">
        <p>We retain data only as long as needed for the purposes described:</p>
        <div className="grid gap-3">
          <LegalDefinition
            term="Account Data"
            desc="Retained while your account is active, then for a reasonable period to close the account and meet legal obligations."
          />
          <LegalDefinition
            term="Customer Content"
            desc="Retained until you delete it or your workspace is deleted, subject to backups."
          />
          <LegalDefinition
            term="Backups"
            desc="May persist for up to 30–90 days after deletion for disaster recovery."
          />
          <LegalDefinition
            term="Logs and security records"
            desc="Typically 30–180 days, longer if needed for investigations or legal compliance."
          />
          <LegalDefinition
            term="Billing records"
            desc="Retained as required by tax and accounting laws."
          />
        </div>
        <p>You can request deletion as described below.</p>
      </LegalSection>

      <LegalSection num={11} title="Security measures">
        <p>
          We use administrative, technical, and organizational measures
          designed to protect information, such as:
        </p>
        <LegalBulletList
          items={[
            "Access controls and least-privilege permissions",
            "Encryption in transit (TLS) and encryption at rest where supported",
            "Monitoring, rate limiting, and anomaly detection",
            "Secure development practices and vulnerability management",
          ]}
        />
        <p className="text-sm text-chrome/80 italic">
          No system is 100% secure. You are responsible for using strong
          passwords and safeguarding access credentials.
        </p>
      </LegalSection>

      <LegalSection num={12} title="Your rights and choices">
        <p>Depending on your location, you may have rights to:</p>
        <LegalBulletList
          items={[
            "Access, correct, or delete your Personal Data",
            "Object to or restrict processing",
            "Port your data",
            "Withdraw consent (where processing is based on consent)",
            "Appeal certain automated decisions, where applicable",
          ]}
        />

        <LegalCallout>
          <strong className="text-bone">How to exercise rights:</strong>{" "}
          Email{" "}
          <LegalLink href="mailto:privacy@elarislabs.ai">
            privacy@elarislabs.ai
          </LegalLink>{" "}
          with your request. We may need to verify your identity.
        </LegalCallout>

        <div className="pt-2">
          <h3 className="text-base font-semibold tracking-tight mb-3 text-bone">
            For California residents (CCPA/CPRA)
          </h3>
          <LegalBulletList
            items={[
              'We do not "sell" Personal Data in the traditional sense.',
              'If we "share" data for cross-context behavioral advertising (if enabled), you can opt out via our cookie preferences center.',
              "You may designate an authorized agent to submit requests.",
            ]}
          />
        </div>
      </LegalSection>

      <LegalSection num={13} title="Children's privacy">
        <p>
          The Services are not intended for children under 13 (or higher age
          where required). We do not knowingly collect Personal Data from
          children.
        </p>
      </LegalSection>

      <LegalSection num={14} title="Changes to this policy">
        <p>
          We may update this policy from time to time. We will post updates on
          this page and update the &quot;Last updated&quot; date. For material
          changes, we may provide additional notice (for example, email or
          in-product notification).
        </p>
      </LegalSection>
    </LegalPage>
  );
}
