import type { Metadata } from "next";
import {
  LegalPage,
  LegalSection,
  LegalSubCard,
  LegalBulletList,
  LegalCallout,
  LegalLink,
  LegalRuleBox,
  LegalSubBulletList,
} from "@/components/legal/LegalShell";

export const metadata: Metadata = {
  title: "Terms and Conditions | ElarisLabs",
  description:
    "The Terms and Conditions governing your access to and use of elarislabs.ai and the ElarisLabs Services.",
  alternates: { canonical: "/terms" },
  robots: { index: true, follow: true },
};

export default function TermsPage() {
  return (
    <LegalPage
      title="Terms and Conditions"
      effective="January 10, 2026"
      updated="January 10, 2026"
    >
      <LegalSection num={1} title="Agreement to these Terms">
        <p>
          These Terms and Conditions (&quot;Terms&quot;) govern your access to
          and use of elarislabs.ai and related Services provided by Elaris
          Labs AI (&quot;ElarisLabs,&quot; &quot;we,&quot; &quot;us&quot;).
        </p>
        <p>
          By using the Services, you agree to these Terms. If you are using
          the Services on behalf of an organization, you represent you have
          authority to bind that organization, and &quot;you&quot; includes
          the organization.
        </p>
      </LegalSection>

      <LegalSection num={2} title="Eligibility">
        <p>
          You must be legally able to form a contract in your jurisdiction.
          The Services are not intended for children under 13 (or higher age
          where required).
        </p>
      </LegalSection>

      <LegalSection num={3} title="Accounts and workspace administration">
        <LegalBulletList
          items={[
            "You must provide accurate account information and keep it updated.",
            "You are responsible for all activity under your account and for maintaining the confidentiality of credentials.",
            "Workspace admins may manage users, permissions, and connected integrations.",
          ]}
        />
      </LegalSection>

      <LegalSection num={4} title="Subscriptions, trials, and payments">
        <LegalBulletList
          items={[
            "Some features require a paid subscription. Pricing, billing cycle, and plan details are shown at checkout or in your order form.",
            "Taxes may apply. You are responsible for all applicable taxes unless otherwise stated.",
            "Trials (if offered) may convert to paid unless canceled before the trial ends.",
            "We may use third-party payment processors.",
          ]}
        />
      </LegalSection>

      <LegalSection num={5} title="Using the Services: acceptable use">
        <p>
          You agree not to misuse the Services. You must not, and must not
          allow others to:
        </p>

        <div className="space-y-4">
          <LegalRuleBox title="Break the law or violate rights" tone="danger">
            <LegalSubBulletList
              items={[
                "Use the Services for unlawful activities",
                "Infringe or misappropriate intellectual property, privacy, or publicity rights",
                "Upload content you do not have permission to use",
              ]}
            />
          </LegalRuleBox>

          <LegalRuleBox
            title="Generate or distribute harmful content"
            tone="danger"
          >
            <LegalSubBulletList
              items={[
                "Content that is illegal, exploitative, or abusive",
                "Content that meaningfully facilitates wrongdoing (fraud, scams, malware)",
                "Content that promotes violence or harassment",
              ]}
            />
          </LegalRuleBox>

          <LegalRuleBox title="Security and platform abuse" tone="danger">
            <LegalSubBulletList
              items={[
                "Attempt to gain unauthorized access, probe, or scan systems",
                "Reverse engineer or attempt to extract model weights or underlying source code (except to the extent the restriction is prohibited by law)",
                "Interfere with service integrity (rate abuse, scraping beyond published limits, bypassing safeguards)",
              ]}
            />
          </LegalRuleBox>

          <LegalRuleBox title="High-risk decisions" tone="warn">
            <p>
              Do not rely on Outputs for medical, legal, financial, or other
              professional advice without qualified human review.
            </p>
          </LegalRuleBox>
        </div>

        <p className="text-sm italic text-chrome/80">
          We may suspend or terminate access for violations.
        </p>
      </LegalSection>

      <LegalSection num={6} title="AI Outputs: important disclaimers">
        <LegalCallout variant="warn">
          <strong className="text-brass">Important.</strong> Outputs are
          generated by probabilistic systems and may be incorrect, incomplete,
          non-unique, or unsuitable.
        </LegalCallout>
        <LegalBulletList
          items={[
            "You are responsible for reviewing Outputs before use, including legal review where needed (for example, advertising compliance, claims substantiation, IP clearance).",
            "We do not guarantee that Outputs will be original or that they will not resemble content generated for other users.",
          ]}
        />
      </LegalSection>

      <LegalSection num={7} title="Customer Content, Outputs, and licenses">
        <LegalSubCard title="A. Your content">
          <p>
            You retain ownership of Customer Content you submit, subject to
            the rights you grant in these Terms.
          </p>
          <p>
            You grant ElarisLabs a non-exclusive, worldwide, royalty-free
            license to host, store, reproduce, process, and display Customer
            Content solely to:
          </p>
          <LegalSubBulletList
            items={[
              "Provide and maintain the Services",
              "Generate Outputs and variants you request",
              "Enforce safety, security, and compliance",
              "Provide support and troubleshoot issues",
            ]}
          />
        </LegalSubCard>

        <LegalSubCard title="B. Outputs">
          <p>As between you and ElarisLabs, and to the extent permitted by law:</p>
          <LegalSubBulletList
            items={[
              "You own the Outputs generated for you from your Customer Content, if any ownership rights exist.",
              "ElarisLabs assigns to you any transferable rights it may have in those Outputs.",
            ]}
          />
        </LegalSubCard>

        <LegalSubCard title="C. Feedback">
          <p>
            If you provide feedback (ideas, suggestions, improvements), you
            grant us the right to use it without restriction or compensation.
          </p>
        </LegalSubCard>
      </LegalSection>

      <LegalSection num={8} title="Model improvement and data controls">
        <p>
          Our handling of prompts and Outputs for model improvement is
          described in our Privacy Policy, including opt-in controls and
          safety review carve-outs.
        </p>
        <LegalCallout>
          If your organization requires a DPA, SCCs, or enterprise controls,
          contact{" "}
          <LegalLink href="mailto:sales@elarislabs.ai">
            sales@elarislabs.ai
          </LegalLink>
          .
        </LegalCallout>
      </LegalSection>

      <LegalSection num={9} title="Intellectual property in the Services">
        <p>
          ElarisLabs and its licensors own the Services, including software,
          templates, workflows, UI, and underlying technology, excluding
          Customer Content and Outputs as described above.
        </p>
        <p>
          You may not copy, modify, distribute, sell, or lease any part of the
          Services unless expressly permitted.
        </p>
      </LegalSection>

      <LegalSection num={10} title="Third-party services and integrations">
        <p>
          The Services may integrate with third-party services (for example,
          analytics, storage, social platforms, ad platforms). Your use of
          third-party services is governed by their terms and policies. We
          are not responsible for third-party services.
        </p>
      </LegalSection>

      <LegalSection num={11} title="Confidentiality (for business users)">
        <p>
          If you access non-public features, betas, or confidential materials,
          you agree not to disclose them without our permission. Additional
          confidentiality terms may apply in an order form or NDA.
        </p>
      </LegalSection>

      <LegalSection num={12} title="Suspension and termination">
        <LegalBulletList
          items={[
            "You may stop using the Services at any time.",
            "We may suspend or terminate access if you violate these Terms, if your use risks harm to others, or if required by law.",
            "Upon termination, your right to use the Services ends. Certain sections survive termination (including IP, disclaimers, limitation of liability, and dispute terms).",
          ]}
        />
      </LegalSection>

      <LegalSection num={13} title="Disclaimers">
        <LegalCallout>
          <p className="mb-3 uppercase text-xs tracking-wide text-chrome">
            The Services are provided &quot;as is&quot; and &quot;as
            available.&quot; To the maximum extent permitted by law:
          </p>
          <LegalBulletList
            items={[
              "We disclaim all warranties, express or implied, including merchantability, fitness for a particular purpose, and non-infringement.",
              "We do not warrant that the Services will be uninterrupted, error-free, or that Outputs will be accurate or suitable.",
            ]}
          />
        </LegalCallout>
      </LegalSection>

      <LegalSection num={14} title="Limitation of liability">
        <LegalCallout>
          <p className="mb-3 uppercase text-xs tracking-wide text-chrome">
            To the maximum extent permitted by law:
          </p>
          <LegalBulletList
            items={[
              "ElarisLabs will not be liable for indirect, incidental, special, consequential, or punitive damages, or any loss of profits, revenue, data, or goodwill.",
              "ElarisLabs' total liability for any claim relating to the Services will not exceed the amount paid by you to ElarisLabs for the Services in the 12 months before the event giving rise to the claim, or USD 100 if you have not paid any amounts.",
            ]}
          />
        </LegalCallout>
        <p className="text-sm italic text-chrome/80">
          Some jurisdictions do not allow certain limitations, so these limits
          may not apply to you in full.
        </p>
      </LegalSection>

      <LegalSection num={15} title="Indemnification">
        <p>
          If you are using the Services for business, you agree to indemnify
          and hold harmless ElarisLabs from claims arising out of:
        </p>
        <LegalBulletList
          items={[
            "Your Customer Content",
            "Your use of Outputs",
            "Your violation of these Terms or applicable law",
          ]}
        />
      </LegalSection>

      <LegalSection num={16} title="Governing law and dispute resolution">
        <p>
          These Terms are governed by the laws of [Jurisdiction], excluding
          conflict of laws rules.
        </p>
        <LegalSubCard title="Dispute resolution">
          <LegalSubBulletList
            items={[
              "Courts located in [Venue] will have jurisdiction, unless your order form specifies otherwise.",
              "Alternatively, if you prefer arbitration, insert your arbitration clause here (many SaaS companies do).",
            ]}
          />
        </LegalSubCard>
      </LegalSection>

      <LegalSection num={17} title="Changes to these Terms">
        <p>
          We may update these Terms from time to time. We will post the
          updated Terms and update the &quot;Last updated&quot; date. If
          changes are material, we may provide additional notice.
        </p>
      </LegalSection>

      <LegalSection num={18} title="Contact">
        <LegalCallout>
          Questions about these Terms:{" "}
          <LegalLink href="mailto:legal@elarislabs.ai">
            legal@elarislabs.ai
          </LegalLink>
        </LegalCallout>
      </LegalSection>
    </LegalPage>
  );
}
